all:
  hosts:
    haremvote:
      ansible_host: oracle1.samplayskeys.ts.net
      ansible_user: sfadmin
      ansible_ssh_private_key_file: ~/.ssh/ssh-key-main-personal-11-25.key

      # For non-root user with sudo:
      # ansible_user: deploy
      # ansible_become: true
      # ansible_become_method: sudo
